#

GET http://localhost:5000/Spp

###
GET http://localhost:5000/Spp/1

###
POST http://localhost:5000/Spp
Content-Type: application/json

{
    "name": "Hapiss",
    "email": "hapis@gmail.com",
    "gender": "Male"
}

###
PATCH http://localhost:5000/Spp/1
Content-Type: application/json

{
    "name": "Mardi",
    "email": "hapis@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/Spp/1


