### Spp Restful-Api
GET http://localhost:5000/Spp

###
GET http://localhost:5000/Spp/1

###
POST http://localhost:5000/Spp
Content-Type: application/json

{
    "tahun": "2023",
    "nominal": "330000"
}

###
PATCH http://localhost:5000/Spp/2
Content-Type: application/json

{
    "tahun": "2023",
    "nominal": "290000"
}

###
DELETE http://localhost:5000/Spp/2



### Siswa Restful-Api
GET http://localhost:5000/siswa

###
GET http://localhost:5000/siswa/1234567890

###
POST http://localhost:5000/siswa
Content-Type: application/json

{
    "nisn": "1234567891",
    "nis": "12345677",
    "nama": "adi",
    "id_kelas": "1",
    "alamat": "jl. sangkuriang",
    "no_telp": "087765451010",
    "id_spp": "1"
}

###
PATCH http://localhost:5000/siswa/1234567891
Content-Type: application/json

{
    "nisn": "1234567891",
    "nis": "12345673",
    "nama": "udin",
    "id_kelas": "2",
    "alamat": "jl. kopi",
    "no_telp": "084355672830",
    "id_spp": "1"
}
###
DELETE http://localhost:5000/siswa/1234567891



### Kelas Restful-Api
GET http://localhost:5000/kelas

###
GET http://localhost:5000/kelas/1

###
POST http://localhost:5000/kelas
Content-Type: application/json

{
    "nama_kelas": "XII-RPL",
    "kompetensi_keahlian": "Rekayasa Perangkat Lunak"
}

###
PATCH http://localhost:5000/kelas/2
Content-Type: application/json

{
    "nama_kelas": "XII-TKJ",
    "kompetensi_keahlian": "Teknologi Komputer dan Jaringan"
}
###
DELETE http://localhost:5000/kelas/2



### Petugas Restful-Api
GET http://localhost:5000/Petugas

###
GET http://localhost:5000/Petugas/1

###
POST http://localhost:5000/Petugas
Content-Type: application/json

{
    "username": "dani",
    "password": "123",
    "nama_petugas": "dani ramadhan",
    "level": "petugas"
}

###
PATCH http://localhost:5000/petugas/2
Content-Type: application/json

{
    "username": "syahrul",
    "password": "123",
    "nama_petugas": "dani ramadhan",
    "level": "petugas"
}
###
DELETE http://localhost:5000/petugas/2



### Pembayaran Restful-Api
GET http://localhost:5000/pembayaran

###
GET http://localhost:5000/pembayaran/1

###
POST http://localhost:5000/pembayaran
Content-Type: application/json

{
    "username": "dani",
    "password": "123",
    "nama_pembayaran": "dani ramadhan",
    "level": "pembayaran"
}

###
PATCH http://localhost:5000/pembayaran/2
Content-Type: application/json

{
    "username": "syahrul",
    "password": "123",
    "nama_pembayaran": "dani ramadhan",
    "level": "pembayaran"
}
###
DELETE http://localhost:5000/pembayaran/2
